apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-puller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: image-puller
  project: default
  source:
    path: charts/image-puller
    repoURL: https://github.com/rhpds/llm-d-intro-automation
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
