apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: redhat-ods-operator
  project: default
  ignoreDifferences:
    - group: kubeflow.org
      kind: Notebook
      jsonPointers:
        - /spec/template/spec/containers/0/env
  source:
    helm:
       values: |
{{ .Values | toYaml | indent 9 }}
    path: charts/openshift-ai
    repoURL: https://github.com/rhpds/llm-d-intro-automation
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
